// <auto-generated />
using CatalogService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251129094244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.CatalogBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CatalogBrands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dell"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogBrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogBrandId");

                    b.HasIndex("CatalogTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("Price");

                    b.ToTable("CatalogItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 50,
                            CatalogBrandId = 1,
                            CatalogTypeId = 1,
                            Description = "Latest flagship smartphone with advanced AI features",
                            ImageUrl = "/images/galaxy-s24.jpg",
                            Name = "Samsung Galaxy S24",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 30,
                            CatalogBrandId = 2,
                            CatalogTypeId = 1,
                            Description = "Apple's premium smartphone with titanium design",
                            ImageUrl = "/images/iphone-15-pro.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 1199.99m
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 100,
                            CatalogBrandId = 3,
                            CatalogTypeId = 3,
                            Description = "Industry-leading noise-canceling headphones",
                            ImageUrl = "/images/sony-wh-1000xm5.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 25,
                            CatalogBrandId = 2,
                            CatalogTypeId = 2,
                            Description = "Powerful laptop for professionals with M3 Max chip",
                            ImageUrl = "/images/macbook-pro-16.jpg",
                            Name = "MacBook Pro 16",
                            Price = 2499.99m
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 40,
                            CatalogBrandId = 5,
                            CatalogTypeId = 2,
                            Description = "Premium Windows laptop with stunning display",
                            ImageUrl = "/images/dell-xps-15.jpg",
                            Name = "Dell XPS 15",
                            Price = 1799.99m
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CatalogType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CatalogTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Monitor"
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CatalogItem", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.CatalogBrand", "CatalogBrand")
                        .WithMany()
                        .HasForeignKey("CatalogBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.CatalogType", "CatalogType")
                        .WithMany()
                        .HasForeignKey("CatalogTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogBrand");

                    b.Navigation("CatalogType");
                });
#pragma warning restore 612, 618
        }
    }
}
